### ISSUE TITLE
[B] - Game doesn't refresh level number and level variables after restart

### ISSUE THREAD

**Issue by Shokerlife** [rmnbnd/WarType#10]
Start new game. 
Reach the second level.
Proceed to the end of game.
Click "Return to Main Menu"
Start new game.

Actual result: game starts from second level
Expected result: game refresh level and level variables (speed also).

**Comment by rmnbnd** [comment]
Fixed by commit - c9a3c0b197cc4f802aa109b4f4db7a26ab950411

**Comment by Shokerlife** [comment]
Issue is reproducible. Speed and level logic is nor refreshing.

**Comment by rmnbnd** [comment]
Fixed by commits:
- 70da83766e3279b3437842baeca4a5a5538eaf43
- 778fa1628c751f4899285d77c3828d74cc4c7ab4
