### ISSUE TITLE
[B] - User is able to make Pause after the end of the game

### ISSUE THREAD

**Issue by Shokerlife** [rmnbnd/WarType#2]
1. Proceed to the end of the game.
2. See Game over screen.
3. Put "Ctrl" button on your keyboard.

Expected result: nothing happens
Actual result: game make a pause

**Comment by rmnbnd** [comment]
Fixed by commit - c13728ed8813e1bb26109ac35ca49e84ef904d58

**Comment by rmnbnd** [comment]
Fixed by commit - 788337b8951f4402ed9e22e96f07f141432f34ef
